=== ed-zm/syscat/rlextra-3.2.0/tests/radxml/samples/toykfd.dtd
<!-- DTD for toy KFD -->
<!-- $Header $-->

<!ELEMENT MAXI_ISA_KFD (
                         CUSTOMER_INFO, 
                         AIMS,
                         YOUR_INVESTMENT,
                         RISK_FACTORS,
                         CHARGES_TEXT,
                         CHARGES_TABLE,
                         IMPORTANT_INFO
                         )>
<!ELEMENT PARA (#PCDATA | ITALIC | BOLD)* >			
<!ELEMENT NUMBEREDLIST (#PCDATA)>			
<!ELEMENT BULLETEDLIST (#PCDATA)>	
<!ELEMENT BOLD (#PCDATA | ITALIC | BOLD)*>					
<!ELEMENT ITALIC (#PCDATA | ITALIC | BOLD)*>			
<!ELEMENT CUSTOMER_NAME (#PCDATA)>			
<!ELEMENT BROKER_COMPANY_NAME (#PCDATA)>			
<!ELEMENT BROKER_CONTACT_NAME (#PCDATA)>			
<!ELEMENT FUND_NAME (#PCDATA)>			
<!ELEMENT AMOUNT_INVESTED (#PCDATA)>			

<!ELEMENT CUSTOMER_INFO (
                         CUSTOMER_NAME,
                         BROKER_COMPANY_NAME,
                         BROKER_CONTACT_NAME,
                         FUND_NAME,
                         AMOUNT_INVESTED
                         )>
<!ELEMENT AIMS (PARA+)>
<!ELEMENT YOUR_INVESTMENT (PARA+)>
<!ELEMENT RISK_FACTORS (PARA+)>
<!ELEMENT CHARGES_TEXT (PARA+)>
<!ELEMENT IMPORTANT_INFO (PARA+)>

<!--charges table related - table and row tags-->
<!ELEMENT CHARGES_TABLE (TABLE_ROW*)>
<!ATTLIST CHARGES_TABLE AMOUNT_INVESTED CDATA #REQUIRED>
<!ATTLIST CHARGES_TABLE INITIAL_CHARGE_RATIO CDATA #REQUIRED>
<!ATTLIST CHARGES_TABLE GROWTH_RATE CDATA #REQUIRED>
<!ATTLIST CHARGES_TABLE ANNUAL_CHARGE_RATIO CDATA #REQUIRED>

<!ELEMENT TABLE_ROW (#PCDATA)> <!--should really be empty-->
<!ATTLIST TABLE_ROW YEAR (1|2|3|4|5|6|7|8|9|10) #REQUIRED>
<!ATTLIST TABLE_ROW INVESTED_TO_DATE CDATA #REQUIRED>
<!ATTLIST TABLE_ROW EFFECT_OF_CHARGES CDATA #REQUIRED>
<!ATTLIST TABLE_ROW VALUATION CDATA #REQUIRED>

=== ed-zm/syscat/rlextra-3.2.0/tests/radxml/samples/toykfd.xml
<?xml version="1.0"?>
<!DOCTYPE MAXI_ISA_KFD SYSTEM "toykfd.dtd">

<MAXI_ISA_KFD>
    <CUSTOMER_INFO>
        <CUSTOMER_NAME>A. Punter</CUSTOMER_NAME>
        <BROKER_COMPANY_NAME>Trotter's Indeendent Savings</BROKER_COMPANY_NAME>
        <BROKER_CONTACT_NAME>Derek Trotter</BROKER_CONTACT_NAME>
        <FUND_NAME>Fidelity American Fund Maxi ISA</FUND_NAME>
        <AMOUNT_INVESTED>5000</AMOUNT_INVESTED>
    </CUSTOMER_INFO>

    <AIMS>
        <PARA>Aims <ITALIC>spam spam <BOLD>spam</BOLD> spam spam</ITALIC>. </PARA>
        <PARA>Eggs eggs eggs eggs eggs. </PARA>
    </AIMS>

    <YOUR_INVESTMENT>
        <PARA><BOLD>Your <ITALIC>investment spam</ITALIC> spam spam spam spam. </BOLD></PARA>
        <PARA>Eggs eggs eggs eggs eggs. </PARA>
    </YOUR_INVESTMENT>

    <RISK_FACTORS>
        <PARA>Risk factor spam spam spam spam spam. </PARA>
        <PARA>Eggs eggs eggs eggs eggs. </PARA>
    </RISK_FACTORS>

    <CHARGES_TEXT>
        <PARA>Charges explanation spam spam spam spam spam. </PARA>
        <PARA>Eggs eggs eggs eggs eggs. </PARA>
    </CHARGES_TEXT>

    <CHARGES_TABLE  AMOUNT_INVESTED="5000"
                    INITIAL_CHARGE_RATIO="0.0325"
                    GROWTH_RATE="0.07"
                    ANNUAL_CHARGE_RATIO="0.0168">
        <TABLE_ROW  YEAR="1"
                    INVESTED_TO_DATE="5000"
                    EFFECT_OF_CHARGES="370.58" 
                    VALUATION="5353.92"/>
        <TABLE_ROW  YEAR="2"
                    INVESTED_TO_DATE="5000"
                    EFFECT_OF_CHARGES="492.76" 
                    VALUATION="5632.46"/>
        <TABLE_ROW  YEAR="3"
                    INVESTED_TO_DATE="5000"
                    EFFECT_OF_CHARGES="492.76" 
                    VALUATION="5632.46"/>
        <TABLE_ROW  YEAR="5"
                    INVESTED_TO_DATE="5000"
                    EFFECT_OF_CHARGES="779.01" 
                    VALUATION="6233.75"/>
        <TABLE_ROW  YEAR="10"
                    INVESTED_TO_DATE="5000"
                    EFFECT_OF_CHARGES="1802.76" 
                    VALUATION="8032.99"/>
    </CHARGES_TABLE>

    <IMPORTANT_INFO>
        <PARA>Really important spam spam spam spam spam. </PARA>
        <PARA>Eggs eggs eggs eggs eggs. </PARA>
    </IMPORTANT_INFO>
</MAXI_ISA_KFD>
